version: "3"

services:
  gogs:
    image: gogs/gogs:latest
    container_name: "gogs"
    volumes:
      - "/docker/gogs/data:/data"
    ports:
      - "10022:22"  ## change, if needed
      - "3000:3000" ## change, if needed
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    container_name: "gogs-db"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: gogs
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass

volumes:
  gogs_data:
  pg_data:
