version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # admin, can take off to save configs or change port
      - '443:443'
    volumes:
      - /docker/nginx_proxy/data:/data
      - /docker/nginx_proxy/letsencrypt:/etc/letsencrypt
      