services:
  nginx:
    container_name: 'web-server'
    image: nginx:latest
    ports:
      - "80:80" 
   #  - "443:443" # SSL
    volumes:
      - /var/www/html:/usr/share/nginx/html
    restart: always