FROM ubuntu:latest
FROM steamcmd/steamcmd:latest

MAINTAINER Joyki

RUN apt update && apt upgrade -y 
RUN apt install -y software-properties-common lsb-release lib32gcc-s1 ca-certificates libc6-dev build-essential 
RUN dpkg --add-architecture i386  
RUN add-apt-repository multiverse -y 
RUN apt update  
RUN apt-get upgrade -y  
RUN adduser steam

USER steam
ENV HOME /home/steam
WORKDIR /home/steam
VOLUME /home/steam

RUN cd /home/steam 
RUN mkdir /home/steam/valheim
RUN steamcmd +force_install_dir /home/steam/valheim +login anonymous +app_update 896660 validate +quit

ENV Servername=NoNameSet
ENV Seed=freetouse
ENV Passwort=secret

EXPORT templdpath=$LD_LIBRARY_PATH
EXPORT LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
EXPORT SteamAppId=892970
EXPORT LD_LIBRARY_PATH=$templdpath

CMD ["/home/steam/valheim/valheim_server.x86_64 -name "$Servername" -port 2456 -world "$Seed" -password "$Passwort" -crossplay"]

EXPOSE 2456-2457