
FROM ubuntu:latest
FROM steamcmd/steamcmd:latest

RUN echo "Install Requirements"
RUN apt update && apt upgrade -y
RUN apt install -y software-properties-common lsb-release lib32gcc-s1 ca-certificates libc6-dev build-essential
RUN dpkg --add-architecture i386
RUN add-apt-repository multiverse -y
RUN apt update
RUN apt-get upgrade -y
RUN apt install -y software-properties-common lsb-release lib32gcc-s1 ca-certificates libc6-dev build-essential

RUN adduser steam
USER steam
ENV HOME /home/steam
RUN chown -R steam /home/steam
WORKDIR /home/steam
VOLUME /home/steam

RUN mkdir /home/steam/valheim ; steamcmd +force_install_dir /home/steam/valheim +login anonymous +app_update 896660 validate +quit

COPY start.sh  /home/steam/valheim/

USER root
RUN chmod +x /home/steam/valheim/start.sh
USER steam

ENV SERVER=NoNameSet
ENV SEED=freetouse
ENV PASSWORD=secret

RUN echo "Start Server"
RUN echo "Settings. Servername: $Servername " $SERVER

CMD [ "/home/steam/valheim/start.sh", $SERVER ,$SEED ,$PASSWORD ]
#CMD [$Servername,$Seed,$Passwort]

EXPOSE 2456-2457
