services:
    cadvisor:
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        ports:
            - 8081:8080 # change if needed
        container_name: cadvisor
        privileged: true
        devices:
            - /dev/kmsg
        image: gcr.io/cadvisor/cadvisor:latest